components:
  frontend:
    envOverrides:
      - name: PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: http://otel-demo-collector.${EXTERNAL_IP}.nip.io/v1/traces

  frontendProxy:
    ingress:
      enabled: true
      hosts:
        - host: otel-demo.${EXTERNAL_IP}.nip.io
          paths:
            - path: /
              pathType: Prefix
              port: 8080

opentelemetry-collector:
  ingress:
    enabled: true
    hosts:
      - host: otel-demo-collector.${EXTERNAL_IP}.nip.io
        paths:
          - path: /
            pathType: Prefix
            port: 4318
